package com.wsy.newdemoapplication.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import greendaobean.TestGreenDaoBean;
import greendaobean.Clazz;
import greendaobean.User;

import com.wsy.newdemoapplication.dao.TestGreenDaoBeanDao;
import com.wsy.newdemoapplication.dao.ClazzDao;
import com.wsy.newdemoapplication.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testGreenDaoBeanDaoConfig;
    private final DaoConfig clazzDaoConfig;
    private final DaoConfig userDaoConfig;

    private final TestGreenDaoBeanDao testGreenDaoBeanDao;
    private final ClazzDao clazzDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testGreenDaoBeanDaoConfig = daoConfigMap.get(TestGreenDaoBeanDao.class).clone();
        testGreenDaoBeanDaoConfig.initIdentityScope(type);

        clazzDaoConfig = daoConfigMap.get(ClazzDao.class).clone();
        clazzDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        testGreenDaoBeanDao = new TestGreenDaoBeanDao(testGreenDaoBeanDaoConfig, this);
        clazzDao = new ClazzDao(clazzDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(TestGreenDaoBean.class, testGreenDaoBeanDao);
        registerDao(Clazz.class, clazzDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        testGreenDaoBeanDaoConfig.clearIdentityScope();
        clazzDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public TestGreenDaoBeanDao getTestGreenDaoBeanDao() {
        return testGreenDaoBeanDao;
    }

    public ClazzDao getClazzDao() {
        return clazzDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
